name = "duckduckgo-ai"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]

[dev]
ip = "127.0.0.1"

[vars]
API_KEY = "sk1234568888no"

[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "9c8cf0284ac540fd94dfe6d2e2c9adca"
